In [1]:
import requests
import pandas as pd

In [2]:
url = 'https://api.pushshift.io/reddit/search/submission' #starter url

In [85]:
#adding parameters to search to drill down to the subreddits
params = {
    'subreddit': 'malefashionadvice',
    'size': 500,
    'before': 1574922367
}

1st before: 'created_utc': 1579551539,
2nd before: 'created_utc': 1578989697,
3rd before: 'created_utc': 1578492996,
4th before: 'created_utc': 1578015570,
5th before: 'created_utc': 1577523589,
6th before: 'created_utc': 1576963900,
7th before: 'created_utc': 1576360643,
8th before: 'created_utc': 1575861593,
9th before: 'created_utc': 1575364094,
10th before: 'created_utc': 1574922367,

In [86]:
res = requests.get(url, params)

In [87]:
res.status_code

200

In [88]:
data = res.json()

In [89]:
posts = data['data']

In [90]:
len(posts)

500

In [83]:
posts[-1]

{'all_awardings': [],
 'allow_live_comments': False,
 'author': 'JhinOnRocks',
 'author_flair_css_class': None,
 'author_flair_richtext': [],
 'author_flair_text': None,
 'author_flair_type': 'text',
 'author_fullname': 't2_4xtw58wh',
 'author_patreon_flair': False,
 'awarders': [],
 'can_mod_post': False,
 'contest_mode': False,
 'created_utc': 1574922367,
 'domain': 'self.malefashionadvice',
 'full_link': 'https://www.reddit.com/r/malefashionadvice/comments/e2tyde/looking_for_boots_recommendations/',
 'gildings': {},
 'id': 'e2tyde',
 'is_crosspostable': False,
 'is_meta': False,
 'is_original_content': False,
 'is_reddit_media_domain': False,
 'is_robot_indexable': False,
 'is_self': True,
 'is_video': False,
 'link_flair_background_color': '',
 'link_flair_richtext': [],
 'link_flair_text_color': 'dark',
 'link_flair_type': 'text',
 'locked': False,
 'media_only': False,
 'no_follow': True,
 'num_comments': 2,
 'num_crossposts': 0,
 'over_18': False,
 'parent_whitelist_status': 'all_ads',
 'permalink': '/r/malefashionadvice/comments/e2tyde/looking_for_boots_recommendations/',
 'pinned': False,
 'pwls': 6,
 'removed_by': 'moderator',
 'retrieved_on': 1574922368,
 'score': 1,
 'selftext': '[removed]',
 'send_replies': True,
 'spoiler': False,
 'steward_reports': [],
 'stickied': False,
 'subreddit': 'malefashionadvice',
 'subreddit_id': 't5_2r65t',
 'subreddit_subscribers': 2228507,
 'subreddit_type': 'public',
 'thumbnail': 'self',
 'title': 'Looking for Boots recommendations!',
 'total_awards_received': 0,
 'url': 'https://www.reddit.com/r/malefashionadvice/comments/e2tyde/looking_for_boots_recommendations/',
 'whitelist_status': 'all_ads',
 'wls': 6}

In [10]:
df = pd.DataFrame(posts)

In [11]:
df.head()

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,suggested_sort,media,media_embed,secure_media,secure_media_embed,crosspost_parent,crosspost_parent_list,media_metadata,author_cakeday,steward_reports
0,[],False,FabricDome,None,[],None,text,t2_tg448,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,slavegaius87,None,[],None,text,t2_gmhat,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,darryljenks,None,[],None,text,t2_h5qyx,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,DAT_DROP,None,[],None,text,t2_mp8wdji,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,yamarobotron-DX7,None,[],None,text,t2_2p2gjd3s,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df1 = pd.DataFrame(posts)
df1.head()

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,secure_media,secure_media_embed,author_flair_background_color,author_flair_text_color,suggested_sort,distinguished,crosspost_parent,crosspost_parent_list,media_metadata,author_cakeday
0,[],False,mjg713,None,[],None,text,t2_t6sq7,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,QuantumShit00,None,[],None,text,t2_3plilc87,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,TommyBoyTime,None,[],None,text,t2_2g3w3r8k,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,mjg713,None,[],None,text,t2_t6sq7,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,Atlantic-Records,None,[],None,text,t2_3nv4783p,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df2 = pd.DataFrame(posts)
df2.head()

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,media_embed,secure_media,secure_media_embed,crosspost_parent,crosspost_parent_list,author_flair_background_color,author_flair_text_color,media_metadata,suggested_sort,distinguished
0,[],False,BeastlyPharoah,None,[],None,text,t2_6bdx2,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,Plebbinn,None,[],None,text,t2_23x7l6f3,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,123123fffffff,None,[],None,text,t2_4sy6ggvi,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,HankRHenry,None,[],None,text,t2_ke8qr,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,213_,None,[],None,text,t2_nm5bgac,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
df3 = pd.DataFrame(posts)
df3.head()

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,crosspost_parent,crosspost_parent_list,media_metadata,author_flair_background_color,author_flair_text_color,distinguished,suggested_sort,author_cakeday,banned_by,edited
0,[],False,rafwiggumredux,None,[],None,text,t2_2idwl2sd,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,BladeRunner2098,None,[],None,text,t2_3d7pubkf,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,InclusivePhitness,None,[],None,text,t2_fc0b6,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,monox60,None,[],None,text,t2_1r4f5n9,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,jsbsjfjsj,None,[],None,text,t2_7cju84y,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
df4 = pd.DataFrame(posts)
df4.head()

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,media_embed,secure_media,secure_media_embed,post_hint,preview,crosspost_parent,crosspost_parent_list,suggested_sort,author_cakeday,distinguished
0,[],False,justingains,None,[],None,text,t2_vz1oc,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,TheQori,None,[],None,text,t2_fg7a6,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,Locke3,None,[],None,text,t2_7ak1g,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,dee_blay,None,[],None,text,t2_ssylbud,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,Unique_the_Vision,None,[],None,text,t2_516fbenr,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
df5 = pd.DataFrame(posts)
df5.head()

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,crosspost_parent_list,author_flair_background_color,author_flair_text_color,suggested_sort,media,media_embed,secure_media,secure_media_embed,media_metadata,distinguished
0,[],False,bluefirecorp,None,[],None,text,t2_610p9,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,bluefirecorp,None,[],None,text,t2_610p9,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,brosales91,None,[],None,text,t2_2jjgzzi0,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,MaxUtilPerUSD,None,[],None,text,t2_n998l,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,stjornuryk,None,[],None,text,t2_gxs6s,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
df6 = pd.DataFrame(posts)
df6.head()

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,author_flair_background_color,author_flair_text_color,suggested_sort,distinguished,media,media_embed,secure_media,secure_media_embed,author_cakeday,media_metadata
0,[],False,backdora_da_explora,None,[],None,text,t2_8etka,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,Formallyinformal99,None,[],None,text,t2_47cfh2dk,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,Oliverdirtyb,None,[],None,text,t2_2x1qftyq,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,Sn0wlux,None,[],None,text,t2_339c4p4a,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,Sn0wlux,None,[],None,text,t2_339c4p4a,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
df7 = pd.DataFrame(posts)
df7.head()

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,media_metadata,suggested_sort,crosspost_parent,crosspost_parent_list,media,media_embed,secure_media,secure_media_embed,distinguished,banned_by
0,[],False,RSheever,None,[],None,text,t2_4m8bfzfx,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,iEATgrenades,None,[],None,text,t2_9dfyg,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,yeomanscholar,None,[],None,text,t2_5069j,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,Hetalbot,None,[],None,text,t2_7myyv,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,akl091,None,[],None,text,t2_2xda8zri,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
df8 = pd.DataFrame(posts)
df8.head()

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,suggested_sort,media,media_embed,secure_media,secure_media_embed,crosspost_parent,crosspost_parent_list,media_metadata,author_cakeday,removed_by
0,[],False,Taylord12345,None,[],None,text,t2_w5ea8m6,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,jamesrutord,None,[],None,text,t2_3csrl19o,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,francoarias955,None,[],None,text,t2_3f1qjp4m,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,jamesrutord,None,[],None,text,t2_3csrl19o,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,Jarvis_C,None,[],None,text,t2_3hcvd5to,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
df9 = pd.DataFrame(posts)
df9.head()

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,awarders,...,author_flair_text_color,crosspost_parent,crosspost_parent_list,media_metadata,media,media_embed,secure_media,secure_media_embed,distinguished,suggested_sort
0,[],False,psycho-matic,None,[],None,text,t2_1qyqgzq0,False,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,LongJumpingApples,None,[],None,text,t2_3q8nkgup,False,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,samiremersonemiliano,None,[],None,text,t2_377e841y,False,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,xMisterVx,None,[],None,text,t2_jkhgi,False,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,Sensilent,None,[],None,text,t2_1340uc,False,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
df10 = pd.DataFrame(posts)
df10.head()

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,awarders,...,author_flair_text_color,media_metadata,crosspost_parent,crosspost_parent_list,suggested_sort,media,media_embed,secure_media,secure_media_embed,banned_by
0,[],False,jontargy_,None,[],None,text,t2_csldk96,False,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,Super_Saiyan_Ronnie,None,[],None,text,t2_14atlb,False,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,aashouldhelp,None,[],None,text,t2_10y148,False,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,cantaloupem,None,[],None,text,t2_4fpj8ut9,False,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,rickowensismydaddy,None,[],None,text,t2_11rjl42b,False,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
#two oclumns interested in, first is what subreddit it came from, and description from each post
#and third most important is title, first columns to use to feed into and nlp column to start preddicting the subreddit column
dfshort = df[['subreddit', 'selftext', 'title']]
#i don't have a lot of self text

In [93]:
dfshort.head()

,subreddit,selftext,title
0,malefashionadvice,,Fast Drying Mens 100% Cotton Gym Towels
1,malefashionadvice,[removed],Looking For Boots
2,malefashionadvice,,Drew today's outfit
3,malefashionadvice,[removed],Advice for collars for the well dressed Man on...
4,malefashionadvice,Figured maybe I could get some help from other...,"need help finding these mens 3"" or 4"" soffe sh..."

In [94]:
dfshort1 = df1[['subreddit', 'selftext', 'title']]
dfshort1.head()

,subreddit,selftext,title
0,malefashionadvice,"I just got a new job that will require ""Busine...",Is it okay for me to have my work shirts Profe...
1,malefashionadvice,,What is your take on wearing multiple rings as...
2,malefashionadvice,[removed],Tailored Tux shirts
3,malefashionadvice,[removed],Question about getting work shirts professiona...
4,malefashionadvice,[removed],is WTAPS worth it?

In [95]:
dfshort2 = df2[['subreddit', 'selftext', 'title']]
dfshort2.head()

,subreddit,selftext,title
0,malefashionadvice,[removed],Help with suit that would compliment fiance's ...
1,malefashionadvice,,Does anyone know what brand this is?
2,malefashionadvice,[removed],A question about waist size.
3,malefashionadvice,"So I'm getting married in July, in the south, ...",I can't stop thinking about this suit (Wedding...
4,malefashionadvice,[removed],Vans sk8 Hi

In [96]:
dfshort3 = df3[['subreddit', 'selftext', 'title']]
dfshort3.head()

,subreddit,selftext,title
0,malefashionadvice,,Brooks Brothers: What to Buy &amp; What to Avo...
1,malefashionadvice,[removed],All of my jeans rip at the thigh... How can I ...
2,malefashionadvice,[removed],Short sleeve floral shirts
3,malefashionadvice,[removed],My stan smith have begun chipping in less than...
4,malefashionadvice,[removed],Ethical/sustainable brands

In [97]:
dfshort4 = df4[['subreddit', 'selftext', 'title']]
dfshort4.head()

,subreddit,selftext,title
0,malefashionadvice,,Can anyone tell me what boot Joe wears from 'Y...
1,malefashionadvice,[removed],I've decided I want to be a hat guy.
2,malefashionadvice,[removed],Any of you buy anything from SendSalon?
3,malefashionadvice,[removed],Non-iron shirts
4,malefashionadvice,[removed],Is it okay to wear French Cuffs without a blazer?

In [98]:
dfshort5 = df5[['subreddit', 'selftext', 'title']]
dfshort5.head()

,subreddit,selftext,title
0,malefashionadvice,[removed],2020 will be the year of the capes.
1,malefashionadvice,Thoughts?,2020 - Year of the cape?
2,malefashionadvice,[removed],Jean cuffing.
3,malefashionadvice,"I received this as a gift today, and it is my ...",OFF-WHITE - What Do I Do With This Shoestring ...
4,malefashionadvice,[removed],I have a $400 BOSS Store gift card. What shoul...

In [99]:
dfshort6 = df6[['subreddit', 'selftext', 'title']]
dfshort6.head()

,subreddit,selftext,title
0,malefashionadvice,,Does anyone know what jacket Alistair Overeem ...
1,malefashionadvice,,Winter Coat Technical Comparison
2,malefashionadvice,,Got my Wolverine 1000 mile boots resoled...pre...
3,malefashionadvice,,Six Classic Colognes That Will Never Let You Down
4,malefashionadvice,,Six Classic Colognes That Will Never Let You Down

In [100]:
dfshort7 = df7[['subreddit', 'selftext', 'title']]
dfshort7.head()

,subreddit,selftext,title
0,malefashionadvice,I have a budget of 150$ to buy a pair of boots...,"Christmas Shopping, Boots Dilemma, Help me for..."
1,malefashionadvice,,Does anyone know how to fix my dumb act of wip...
2,malefashionadvice,[removed],Wednesdays' Wool Trousers were too grey and plain
3,malefashionadvice,,Why the Codpiece Remains One of Menswear’s Mos...
4,malefashionadvice,,How do you avoid ribbed edges when washing mer...

In [101]:
dfshort8 = df8[['subreddit', 'selftext', 'title']]
dfshort8.head()

           subreddit   selftext                                    title
0  malefashionadvice  [removed]   What size onesie am i supposed to get?
1  malefashionadvice  [removed]  Common Project Chelsea Boots Stitching?
2  malefashionadvice                  What could these go with (outfits)
3  malefashionadvice  [removed]   Common Project Chelsea Boots Stitching
4  malefashionadvice  [removed]  What Color of Undershirt Should I Wear?

In [102]:
dfshort9 = df9[['subreddit', 'selftext', 'title']]
dfshort9.head()

,subreddit,selftext,title
0,malefashionadvice,[removed],Thursday boots explorer
1,malefashionadvice,,Thoughts on these skinnies?
2,malefashionadvice,,What did he done this time?
3,malefashionadvice,I'm a bit lost here. I'd need business style (...,Help finding winter boots that look elegant?
4,malefashionadvice,"Hello guys,\n\nThis is an unusual topic. I am ...",[Fictional Essay] How to Become a Menswear Nerd

In [103]:
dfshort10 = df10[['subreddit', 'selftext', 'title']]
dfshort10.head()

,subreddit,selftext,title
0,malefashionadvice,,First time wearing a scarf and cardigan. What ...
1,malefashionadvice,[removed],Help me with the perfect fit/style for sunglasses
2,malefashionadvice,This might sound like a weird post but I've re...,Tuck your dress shirts in
3,malefashionadvice,[removed],vans shoe sizes
4,malefashionadvice,,Uniqlo - A History of Simplicity to Global Dom...

In [104]:
pdList = [df, df1, df2, df3, df4, df5, df6, df7, df8, df9, df10]
long_df_mens = pd.concat(pdList)

C:\Users\Vera\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [105]:
pdList = [dfshort, dfshort1, dfshort2, dfshort3, dfshort4, dfshort5, dfshort6, dfshort7, dfshort8, dfshort9, dfshort10]
new_df_mens = pd.concat(pdList)

In [106]:
new_df_mens.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5500 entries, 0 to 499
Data columns (total 3 columns):
subreddit    5500 non-null object
selftext     5461 non-null object
title        5500 non-null object
dtypes: object(3)
memory usage: 171.9+ KB

In [107]:
long_df_mens.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5500 entries, 0 to 499
Data columns (total 79 columns):
all_awardings                    5500 non-null object
allow_live_comments              5500 non-null bool
author                           5500 non-null object
author_cakeday                   22 non-null object
author_flair_background_color    413 non-null object
author_flair_css_class           0 non-null object
author_flair_richtext            5437 non-null object
author_flair_text                344 non-null object
author_flair_text_color          413 non-null object
author_flair_type                5437 non-null object
author_fullname                  5437 non-null object
author_patreon_flair             5437 non-null object
author_premium                   4368 non-null object
awarders                         5500 non-null object
banned_by                        39 non-null object
can_mod_post                     5500 non-null bool
contest_mode                     5500 non-null bool
created_utc                      5500 non-null int64
crosspost_parent                 50 non-null object
crosspost_parent_list            50 non-null object
distinguished                    30 non-null object
domain                           5500 non-null object
edited                           3 non-null float64
full_link                        5500 non-null object
gildings                         5500 non-null object
id                               5500 non-null object
is_crosspostable                 5500 non-null bool
is_meta                          5500 non-null bool
is_original_content              5500 non-null bool
is_reddit_media_domain           5500 non-null bool
is_robot_indexable               5500 non-null bool
is_self                          5500 non-null bool
is_video                         5500 non-null bool
link_flair_background_color      5500 non-null object
link_flair_css_class             2939 non-null object
link_flair_richtext              5500 non-null object
link_flair_template_id           3382 non-null object
link_flair_text                  3383 non-null object
link_flair_text_color            5500 non-null object
link_flair_type                  5500 non-null object
locked                           5500 non-null bool
media                            73 non-null object
media_embed                      73 non-null object
media_metadata                   30 non-null object
media_only                       5500 non-null bool
no_follow                        5500 non-null bool
num_comments                     5500 non-null int64
num_crossposts                   5500 non-null int64
over_18                          5500 non-null bool
parent_whitelist_status          5500 non-null object
permalink                        5500 non-null object
pinned                           5500 non-null bool
post_hint                        1020 non-null object
preview                          1020 non-null object
pwls                             5500 non-null int64
removed_by                       541 non-null object
removed_by_category              2295 non-null object
retrieved_on                     5500 non-null int64
score                            5500 non-null int64
secure_media                     73 non-null object
secure_media_embed               73 non-null object
selftext                         5461 non-null object
send_replies                     5500 non-null bool
spoiler                          5500 non-null bool
steward_reports                  5087 non-null object
stickied                         5500 non-null bool
subreddit                        5500 non-null object
subreddit_id                     5500 non-null object
subreddit_subscribers            5500 non-null int64
subreddit_type                   5500 non-null object
suggested_sort                   83 non-null object
thumbnail                        5500 non-null object
thumbnail_height                 867 non-null float64
thumbnail_width                  867 non-null float64
title                            5500 non-null object
total_awards_received            5500 non-null int64
url                              5500 non-null object
whitelist_status                 5500 non-null object
wls                              5500 non-null int64
dtypes: bool(18), float64(3), int64(9), object(49)
memory usage: 2.7+ MB

In [108]:
#i'm going to export to csv just in case
new_df_mens.to_csv('./mens_reddit2.csv')

In [109]:
long_df_mens.to_csv('./total_mens_reddit2.csv')